"""
Test suite for the generation mode functionality of the Knowledge Base system.

This module tests the ability to generate summaries for files that lack them,
update summaries for changed files, and validate the quality of generated summaries.
"""

import pytest
import tempfile
import shutil
import json
import os
import sys
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Import the modules we're testing
from knowledge_base_builder import KnowledgeBaseBuilder
from knowledge_database import KnowledgeDatabase
from markdown_summarizer_v2 import MarkdownSummarizerV2


class TestGenerationMode:
    """Test suite for generation mode functionality."""
    
    def setup_method(self):
        """Set up test environment before each test."""
        # Create temporary directory for tests
        self.temp_dir = tempfile.mkdtemp()
        self.base_path = Path(self.temp_dir)
        
        # Create test database and cache paths
        self.db_path = self.base_path / "test_knowledge_base.json"
        self.cache_path = self.base_path / "test_embeddings_cache.json"
        
        # Create some test markdown files
        self.create_test_files()
        
        # Mock the OpenAI API calls to avoid actual API usage
        self.mock_summarizer_response = {
            'summary': 'Test summary generated by AI',
            'content_length': 100
        }
        
    def teardown_method(self):
        """Clean up after each test."""
        # Remove temporary directory
        shutil.rmtree(self.temp_dir, ignore_errors=True)
    
    def create_test_files(self):
        """Create test markdown files for testing."""
        # File 1: Has content but no summary in database
        (self.base_path / "file1.md").write_text("# Test File 1\n\nThis is test content for file 1.")
        
        # File 2: Has content and will be in database
        (self.base_path / "file2.md").write_text("# Test File 2\n\nThis is test content for file 2.")
        
        # File 3: Has content but will be modified
        (self.base_path / "file3.md").write_text("# Test File 3\n\nThis is test content for file 3.")
        
        # Create a subdirectory with files
        subdir = self.base_path / "subdir"
        subdir.mkdir()
        (subdir / "file4.md").write_text("# Test File 4\n\nThis is test content in subdirectory.")
    
    def create_partial_database(self):
        """Create a database with some files but not all."""
        db = KnowledgeDatabase(str(self.db_path))
        
        # Add file2 to database
        file2_path = self.base_path / "file2.md"
        db.add_file(
            file_path=file2_path,
            summary="Existing summary for file 2",
            content_length=50
        )
        
        # Add file3 to database but with old hash (simulating file change)
        file3_path = self.base_path / "file3.md"
        db.add_file(
            file_path=file3_path,
            summary="Old summary for file 3",
            content_length=50
        )
        # Manually modify the hash to simulate file change
        file3_key = str(file3_path.resolve())
        db.db_data["files"][file3_key]["metadata"]["file_hash"] = "old_hash"
        
        db.save_database()
        return db
    
    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_identify_files_needing_summaries_missing_mode(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test identification of files missing summaries."""
        # Create partial database
        self.create_partial_database()
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test missing mode
        files_needing_summaries = builder.identify_files_needing_summaries("missing")
        
        # Should find file1 and file4 (not in database)
        file_names = [f.name for f in files_needing_summaries]
        assert "file1.md" in file_names
        assert "file4.md" in file_names
        assert "file2.md" not in file_names  # Already has summary
        assert len(files_needing_summaries) == 2

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_identify_files_needing_summaries_outdated_mode(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test identification of outdated files."""
        # Create partial database
        self.create_partial_database()
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test outdated mode
        files_needing_summaries = builder.identify_files_needing_summaries("outdated")
        
        # Should find file3 (hash mismatch) and files not in database
        file_names = [f.name for f in files_needing_summaries]
        assert "file3.md" in file_names  # Modified file
        assert "file1.md" in file_names  # Not in database
        assert "file4.md" in file_names  # Not in database
        assert len(files_needing_summaries) >= 1

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_identify_files_needing_summaries_all_mode(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test identification of all files for regeneration."""
        # Create partial database
        self.create_partial_database()
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test all mode
        files_needing_summaries = builder.identify_files_needing_summaries("all")
        
        # Should find all markdown files
        file_names = [f.name for f in files_needing_summaries]
        assert "file1.md" in file_names
        assert "file2.md" in file_names
        assert "file3.md" in file_names
        assert "file4.md" in file_names
        assert len(files_needing_summaries) == 4

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_generate_summaries_missing_mode(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test summary generation for missing files."""
        # Setup mock summarizer
        mock_summarizer = Mock()
        mock_summarizer.summarize_file.return_value = self.mock_summarizer_response
        mock_summarizer_class.return_value = mock_summarizer
        
        # Create partial database
        self.create_partial_database()
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test generation
        result = builder.generate_summaries("missing")
        
        # Verify results
        assert result["status"] == "completed"
        assert result["mode"] == "missing"
        assert result["files_processed"] >= 1
        assert result["files_failed"] == 0
        
        # Verify files were added to database
        db = KnowledgeDatabase(str(self.db_path))
        file1_key = str((self.base_path / "file1.md").resolve())
        assert db.has_file(file1_key)
        
        file_data = db.get_file_data(file1_key)
        assert file_data["summary"] == self.mock_summarizer_response["summary"]

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_generate_summaries_with_target_files(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test summary generation with specific target files."""
        # Setup mock summarizer
        mock_summarizer = Mock()
        mock_summarizer.summarize_file.return_value = self.mock_summarizer_response
        mock_summarizer_class.return_value = mock_summarizer
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test generation with target files
        result = builder.generate_summaries("all", target_files=["file1.md"])
        
        # Verify only targeted file was processed
        assert result["files_found"] == 1
        assert result["files_processed"] == 1
        
        # Verify only the targeted file was summarized
        assert mock_summarizer.summarize_file.call_count == 1

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_generate_summaries_with_progress_callback(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test summary generation with progress callback."""
        # Setup mock summarizer
        mock_summarizer = Mock()
        mock_summarizer.summarize_file.return_value = self.mock_summarizer_response
        mock_summarizer_class.return_value = mock_summarizer
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Mock progress callback
        progress_callback = Mock()
        
        # Test generation with progress callback
        result = builder.generate_summaries("all", progress_callback=progress_callback)
        
        # Verify callback was called
        assert progress_callback.called
        assert progress_callback.call_count == result["files_processed"]

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_generate_summaries_handles_failures(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test that generation handles failures gracefully."""
        # Setup mock summarizer that fails
        mock_summarizer = Mock()
        mock_summarizer.summarize_file.side_effect = Exception("Simulated failure")
        mock_summarizer_class.return_value = mock_summarizer
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test generation with failures
        result = builder.generate_summaries("all")
        
        # Verify failures were handled
        assert result["status"] == "completed"
        assert result["files_failed"] > 0
        assert result["files_processed"] == 0

    @patch('knowledge_base_builder.QuestionAnswerer')
    @patch('knowledge_base_builder.SemanticSearchV2')
    @patch('knowledge_base_builder.MarkdownSummarizerV2')
    def test_validate_summaries(self, mock_summarizer_class, mock_semantic_class, mock_qa_class):
        """Test summary validation functionality."""
        # Create a database with various scenarios
        db = KnowledgeDatabase(str(self.db_path))
        
        # Add file with good summary
        file1_path = self.base_path / "file1.md"
        db.add_file(
            file_path=file1_path,
            summary="This is a good quality summary with appropriate length for testing validation.",
            content_length=100
        )
        
        # Add file with short summary
        file2_path = self.base_path / "file2.md"
        db.add_file(
            file_path=file2_path,
            summary="Short",  # Too short
            content_length=100
        )
        
        # Add file with long summary
        file3_path = self.base_path / "file3.md"
        long_summary = "This is an extremely long summary that exceeds the recommended length for summaries in our knowledge base system. " * 10
        db.add_file(
            file_path=file3_path,
            summary=long_summary,
            content_length=100
        )
        
        # Add orphaned entry (file doesn't exist)
        orphaned_path = self.base_path / "nonexistent.md"
        db.add_file(
            file_path=orphaned_path,
            summary="Summary for non-existent file",
            content_length=100
        )
        
        db.save_database()
        
        # Create knowledge base builder
        builder = KnowledgeBaseBuilder(
            base_directory=str(self.base_path),
            db_path=str(self.db_path),
            embeddings_cache_path=str(self.cache_path)
        )
        
        # Test validation
        result = builder.validate_summaries()
        
        # Verify validation results
        assert result["total_files"] == 4  # Including orphaned entry
        assert result["files_with_summaries"] >= 3
        assert result["files_with_short_summaries"] >= 1
        assert result["files_with_long_summaries"] >= 1
        assert result["orphaned_database_entries"] >= 1
        assert len(result["consistency_issues"]) >= 3

    def test_knowledge_database_new_methods(self):
        """Test new methods added to KnowledgeDatabase."""
        db = KnowledgeDatabase(str(self.db_path))
        
        # Test has_file method
        file_path = self.base_path / "file1.md"
        file_key = str(file_path.resolve())
        
        assert not db.has_file(file_key)  # File not in database yet
        
        # Add file
        db.add_file(file_path, "Test summary", 100)
        
        assert db.has_file(file_key)  # File now in database
        
        # Test get_file_data method
        file_data = db.get_file_data(file_key)
        assert file_data is not None
        assert file_data["summary"] == "Test summary"
        
        # Test get_all_files_dict method
        all_files = db.get_all_files_dict()
        assert isinstance(all_files, dict)
        assert file_key in all_files


class TestGenerationModeCLI:
    """Test the CLI integration for generation mode."""
    
    def setup_method(self):
        """Set up test environment."""
        self.temp_dir = tempfile.mkdtemp()
        self.base_path = Path(self.temp_dir)
        
    def teardown_method(self):
        """Clean up after tests."""
        shutil.rmtree(self.temp_dir, ignore_errors=True)
    
    @patch('kb_cli.KnowledgeBaseBuilder')
    def test_cli_generate_command_missing_mode(self, mock_builder_class):
        """Test CLI generate command with missing mode."""
        from kb_cli import KnowledgeBaseCLI
        import argparse
        
        # Setup mock builder
        mock_builder = Mock()
        mock_builder.generate_summaries.return_value = {
            "status": "completed",
            "mode": "missing",
            "files_found": 5,
            "files_processed": 4,
            "files_failed": 1,
            "duration_seconds": 30.5
        }
        mock_builder_class.return_value = mock_builder
        
        # Create CLI instance
        cli = KnowledgeBaseCLI()
        cli.builder = mock_builder
        
        # Create mock args
        args = argparse.Namespace(
            mode="missing",
            files=None,
            directory=str(self.base_path),
            db_path="test.json",
            embeddings_cache="test_cache.json"
        )
        
        # Test the command (should not raise exceptions)
        try:
            cli.cmd_generate(args)
            success = True
        except Exception as e:
            success = False
            print(f"CLI command failed: {e}")
        
        assert success
        mock_builder.generate_summaries.assert_called_once()

    @patch('kb_cli.KnowledgeBaseBuilder')
    def test_cli_validate_command(self, mock_builder_class):
        """Test CLI validate command."""
        from kb_cli import KnowledgeBaseCLI
        import argparse
        
        # Setup mock builder
        mock_builder = Mock()
        mock_builder.validate_summaries.return_value = {
            "total_files": 10,
            "files_with_summaries": 8,
            "files_missing_summaries": 2,
            "files_with_short_summaries": 1,
            "files_with_long_summaries": 1,
            "orphaned_database_entries": 0,
            "consistency_issues": ["Issue 1", "Issue 2"]
        }
        mock_builder_class.return_value = mock_builder
        
        # Create CLI instance
        cli = KnowledgeBaseCLI()
        cli.builder = mock_builder
        
        # Create mock args
        args = argparse.Namespace(
            directory=str(self.base_path),
            db_path="test.json",
            embeddings_cache="test_cache.json"
        )
        
        # Test the command
        try:
            cli.cmd_validate(args)
            success = True
        except Exception as e:
            success = False
            print(f"CLI validate command failed: {e}")
        
        assert success
        mock_builder.validate_summaries.assert_called_once()


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v"])